### ISSUE TITLE
ERROR SyntaxError: Unexpected token a

### ISSUE THREAD

**Issue by vyorkin** [danpaz/hubot-travis-ci#1]
I've set all required env variables, but still get this:

```
5-12-12T21:53:26.769649+00:00 app[web.1]: [Sat Dec 12 2015 21:53:26 GMT+0000 (UTC)] INFO hubot-redis-brain: Successfully authenticated to Redis
2015-12-12T21:53:26.656473+00:00 heroku[web.1]: Process exited with status 0
2015-12-12T21:53:26.771367+00:00 app[web.1]: [Sat Dec 12 2015 21:53:26 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
2015-12-12T21:54:01.188589+00:00 app[web.1]: [Sat Dec 12 2015 21:54:01 GMT+0000 (UTC)] ERROR SyntaxError: Unexpected token a
2015-12-12T21:54:01.188593+00:00 app[web.1]:   at Object.parse (native)
2015-12-12T21:54:01.188595+00:00 app[web.1]:   at /app/node_modules/hubot-travis-ci/src/hubot-travis-ci.coffee:50:11, <js>:35:23
2015-12-12T21:54:01.188596+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
2015-12-12T21:54:01.188597+00:00 app[web.1]:   at IncomingMessage.emit (events.js:117:20)
2015-12-12T21:54:01.188598+00:00 app[web.1]:   at _stream_readable.js:944:16
2015-12-12T21:54:01.188598+00:00 app[web.1]:   at process._tickCallback (node.js:448:13)
```

**Comment by danpaz** [comment]
Hmm looks like an error on this line https://github.com/danpaz/hubot-travis-ci/blob/master/src/hubot-travis-ci.coffee#L50.

Possibly `body` is defined but isn't proper JSON. Maybe try logging `body` before that, my guess is the body is an error message or html error page or something that isn't JSON.

**Comment by danpaz** [comment]
I'm going to close this now. If you continue to have issues please let me know.
